# Generated by Django 4.2.4 on 2023-09-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_note_remove_comments_post_id_delete_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='user',
            name='emoji',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
